// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuddywlwymdseuuoozcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1ZGR5d2x3eW1kc2V1dW9vemNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDMwOTQsImV4cCI6MjA2NTMxOTA5NH0.PtT3ZEjZHDYuPopw0aQ8y8vafGiPqBWD_dTc5ot-k9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);